### PR TITLE
Add renewAccessToken functionality

### PR DESCRIPTION
**Pull request by hbakhtiyor**
would be nice to add this (@pauarge)

### CODE REVIEW

**Comment by pauarge** [comment]
Let me check why tests fail and I'll submit a pull request.

**Comment by esteban-uo** [comment]
thanks @hbakhtiyor @pauarge ! I fixed by rolling back some changes not needed (let me know if you wanted another behavior) https://github.com/esteban-uo/picasa/pull/13/commits/d3104989942d4789df281946eb267f5680470f4e

**Comment by esteban-uo** [comment]
btw I mentioned you in the README, thx! :)

**Comment by hbakhtiyor** [comment]
haha, thanks, i'm not even a contributor

**Pull request closed without merging**
